# Generated by Django 3.2.7 on 2021-09-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0002_auto_20210910_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
